image: ubuntu:latest

before_install:
        - apt update
        - apt install -y python3-pip
        - pip3 install pytest

install:
        - echo 'install'

before_script:
        - echo 'before script'

script:
        - pytest

after_success:
        - echo 'success'

after_failure:
        - echo 'failure'

after_script:
        - echo 'after script'
