image: ubuntu:latest

before_install:
        - apt update && apt install -y python3-pytest

install:
        - echo 'install'

before_script:
        - echo 'before script'

script:
        - pytest-3

after_success:
        - echo 'success'

after_failure:
        - echo 'failure'

after_script:
        - echo 'after script'
